INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 102", "Library Lobby & Circulation Desk");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 101A", "Library Cafe Lounge");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 101", "Library Open Stack Study");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 114", "Lecture");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 115", "Group Study");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 116", "Group Study");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 117", "Group Study");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 118", "Library Conference & Training");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 120", "Digital Media Lab");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 121", "Computer Lab");

-- These scripts are designed to insert the room entities to the hsu_library schema
-- Updated 4/9/18 -->
INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 122", "Computer Lab");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 201", "Open Library Collection");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 205", "Collaboration Lab");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 208", "Math Tutorial Lab");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 209", "Fishbowl");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 301", "Library Open Collection");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 307", "Special Collections");

INSERT INTO ROOM
(FACILITIES_ID, NAME)
VALUES
("LIB 308", "Humboldt Room Archives");